### ISSUE TITLE
Transaction is inconsistent in its LAST_INSERT_ID() calls

### ISSUE THREAD

**Issue by jboyens** [nkallen/querulous#6]
One call uses .getLong the other uses .getInt

**Comment by jboyens** [comment]
Patch in

jboyens/querulous@2ba2b993e41bdd57f8505f74d9b2b5ba9e08e1f0
AND
jboyens/querulous@2b1b856370067f4fd15217a52b16158e45742cf5

Two commits because I'm push-happy and dumb.

**Comment by eaceaser** [comment]
merged
